name: Test Artifact Upload
description: Uploads test archives to GCS and runs on-device tests.
inputs:
  type:
    description: "Type of artifacts to upload (ondevice or onhost)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Set env vars
      run: |
        set -x
        if [ "${{ inputs.type }}" == 'ondevice' ]
        then
          echo "ARCHIVE_FILE_PATH=$GITHUB_WORKSPACE/builder_tmp/${{matrix.platform}}_${{matrix.config}}/artifacts.tar" >> $GITHUB_ENV
        elif [ "${{ inputs.type }}" == 'onhost' ]
        then
          echo "ARCHIVE_FILE_PATH=$GITHUB_WORKSPACE/src/out/tmp/${{matrix.platform}}_${{matrix.config}}/${{matrix.platform}}_${{matrix.config}}.tar.xz" >> $GITHUB_ENV
        fi
        echo "PROJECT_NAME=$(gcloud config get-value project)" >> $GITHUB_ENV
        echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
        echo "WORKFLOW=${{github.workflow}}" >> $GITHUB_ENV
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      shell: bash
    - name: Create Test Files Archive
      run: |
        set -x
        if [ "${{ inputs.type }}" == 'ondevice' ]
        then
          python3 $GITHUB_WORKSPACE/tools/create_archive.py --test_infra -d ${{env.ARCHIVE_FILE_PATH}} -s $GITHUB_WORKSPACE/out/${{matrix.target_platform}}_${{matrix.config}}
        elif [ "${{ inputs.type }}" == 'onhost' ]
        then
          python3 $GITHUB_WORKSPACE/tools/create_archive.py --intermediate -d ${{env.ARCHIVE_FILE_PATH}} -s $GITHUB_WORKSPACE/out/${{matrix.target_platform}}_${{matrix.config}} --parallel
        fi
      shell: bash
    - name: Copy Test Files to GCS
      id: upload-test-archive
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ${{env.ARCHIVE_FILE_PATH}}
        destination: ${{env.PROJECT_NAME}}-test-artifacts/${{env.WORKFLOW}}/${{env.GITHUB_RUN_NUMBER}}/${{matrix.platform}}_${{matrix.config}}/
