name: evergreen-arm-hardfp_nightly

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-arm-hardfp
