name: linux

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ main ]
  push:
    branches: [ main ]
  issue_comment:
    types: [ created, edited ]
  workflow_dispatch:

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.action }}"

  # CI:
  #   uses: ./.github/workflows/main.yaml
  #   permissions:
  #     packages: write
  #   with:
  #     platform: $GITHUB_WORKFLOW
