name: raspi-2_nightly_23.lts.1+

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  trigger:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Trigger Nightly
        run: |
          set -x
          gh workflow run raspi-2 --ref main
          echo $?
          gh workflow run raspi-2_23.lts.1+ --ref 23.lts.1+
          echo $?
          gh workflow list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
