name: On device tests (label)
on:
  pull_request:
    types:
      - labeled
jobs:
  initialize:
    name: Cleaning up the PR
    if: github.event.label.name == 'test_labs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Remove label
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            ${{ github.event.pull_request.base.repo.url }}/issues/${{ github.event.number }}/labels/${{ github.event.label.name }}
        shell: bash

  CI:
    needs: initialize
    uses: ./.github/workflows/main_comment.yaml
    permissions:
      packages: write
    with:
      platform: $GITHUB_WORKFLOW
      run_test_labs: true
