name: trigger

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  trigger:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Nightly
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: raspi-2
          token: ${{ secrets.GITHUB_TOKEN }}
