name: win32_nightly

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    uses: ./.github/workflows/main_win.yaml
    permissions:
      packages: write
    with:
      platform: $GITHUB_WORKFLOW

